[build]
  command = "npm run build"
  publish = "public"

[build.secrets_scanning]
  secrets_omit_paths = [
    "public/**" # Ignora tutti i file nella directory di output
  ]

[dev]  
  command = "npm run start"
  port = 8888
  targetPort = 8000
  framework = "gatsby"

[[redirects]]
  from = "https://volontaricivici.netlify.app/*"
  to = "https://www.volontaricivici.sm/:splat"
  status = 301
  force = true