[build]
  command = "npm run build"
  publish = "public"

  [build.secrets_scanning]
    secrets_omit_keys = ["AUTH0_AUDIENCE"]

[dev]  
  command = "npm run start"
  port = 8888
  targetPort = 8000
  framework = "gatsby"

[[redirects]]
  from = "https://volontaricivici.netlify.app/*"
  to = "https://www.volontaricivici.sm/:splat"
  status = 301
  force = true