backend:
  name: git-gateway
  branch: main
media_folder: /content/asset/images/blog
public_folder: /img
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "titolo", widget: "string" }
      - { label: "Sottotitolo", name: "sottotitolo", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Slogan", name: "slogan", widget: "string" }
      - { label: "Data", name: "date", widget: "string" }
      - { label: "Aggiornamento", name: "update", widget: "string" }
      - { label: "Autore", name: "author", widget: "string" }
      - {
          label: "Pubblicato",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - { label: "Immagine principale", name: "featuredImage", widget: "image" }
      - { label: "Immagine laterale", name: "sideImage", widget: "image" }
      - { label: "Corpo", name: "body", widget: "markdown" }
