backend:
  name: git-gateway
  branch: main
media_folder: content/assets/images/blog
public_folder: /img
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Slogan", name: "slogan", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sottotitolo", name: "sottotitolo", widget: "string" }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          options: ["Eventi ed Iniziative", "Progetti"],
        }
      - { label: "Corpo", name: "description", widget: "markdown" }
      - { label: "Autore", name: "author", widget: "string" }
      - {
          label: "Data di pubblicazione",
          name: "date",
          widget: "datetime",
          format: "DD/MM/YYYY",
        }
      - {
          label: "Data di aggiornamento",
          name: "update",
          widget: "datetime",
          format: "DD/MM/YYYY",
        }
      - {
          label: "Pubblicato",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - { label: "Immagine grande", name: "featuredImage", widget: "image" }
      - { label: "Immagine laterale", name: "sideImage", widget: "image" }
